import {loadSecret,loadSetting,saveSetting} from './crypto.js';
import {parseJsonFromText,sleep} from './utils.js';
import {blobFromInline} from './audio.js';
const cooldownKey=(kind,i)=>`cooldown:${kind}:${i}`;
function lines(s){return String(s||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i)}
async function post(url,key,body,provider){const headers={'Content-Type':'application/json'};if(provider==='gemini')headers['x-goog-api-key']=key;else headers.Authorization=`Bearer ${key}`;const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(body)});const raw=await r.text();if(!r.ok){const e=new Error(`${provider} HTTP ${r.status}: ${raw.slice(0,500)}`);e.status=r.status;e.retryAfter=Number(r.headers.get('retry-after')||0);throw e}return JSON.parse(raw)}
async function projectPool(kind){const secret=await loadSecret(kind==='vocab'?'vocabKeys':'speechKeys');const arr=lines(secret);const now=Date.now();const usable=[];for(let i=0;i<arr.length;i++){const until=Number(await loadSetting(cooldownKey(kind,i),0));if(until<=now)usable.push({key:arr[i],index:i})}return usable}
async function markCooldown(kind,index,e){if(e.status!==429&&e.status!==503)return;const sec=e.retryAfter>0?e.retryAfter:3600;await saveSetting(cooldownKey(kind,index),Date.now()+sec*1000)}
function geminiText(response){const parts=response?.candidates?.[0]?.content?.parts||[];for(const p of parts)if(p.text)return p.text;throw new Error('Gemini không trả text')}
function geminiInline(response){const parts=response?.candidates?.[0]?.content?.parts||[];for(const p of parts){const d=p.inlineData||p.inline_data;if(d?.data)return d}throw new Error('Gemini không trả audio')}
export async function enrichBatch(words){const textModel=await loadSetting('textModel','gemini-3.1-flash-lite');const targets=words.map((w,i)=>`${i}. ${w}`).join('\n');const prompt=`You create high-quality English vocabulary flashcards for a Vietnamese adult learner.\nProcess every item in this numbered list:\n${targets}\n\nReturn exactly one JSON object with this shape:\n{"items":[{"index":0,"ipaUS":"/.../","ipaUK":"/.../","meaningVi":"...","partOfSpeech":"noun","exampleEn":"...","exampleVi":"..."}]}\nRules:\n- One item for every input index; preserve index.\n- ipaUS = accurate General American IPA, including / /.\n- ipaUK = accurate modern Standard British IPA, including / /.\n- meaningVi = short natural Vietnamese meaning; max 2 closely related common meanings.\n- partOfSpeech = concise English part of speech.\n- exampleEn = one short natural English sentence using the intended sense.\n- exampleVi = natural Vietnamese translation of exampleEn.\n- No markdown or explanation outside JSON.`;
  const body={contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.15,responseMimeType:'application/json'}};
  const pool=await projectPool('vocab');let last;
  for(const p of pool){try{const resp=await post(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(textModel)}:generateContent`,p.key,body,'gemini');const root=parseJsonFromText(geminiText(resp));return normalizeItems(root.items,words.length)}catch(e){last=e;await markCooldown('vocab',p.index,e);if(![429,500,502,503,504].includes(e.status))break}}
  const groqEnabled=Boolean(await loadSetting('groqEnabled',false));const groqKey=groqEnabled?await loadSecret('groqKey'):'';if(groqKey){try{const model=await loadSetting('groqModel','openai/gpt-oss-20b');const resp=await post('https://api.groq.com/openai/v1/chat/completions',groqKey,{model,messages:[{role:'system',content:'Return JSON only.'},{role:'user',content:prompt}],temperature:0.15,response_format:{type:'json_object'}},'groq');const root=parseJsonFromText(resp?.choices?.[0]?.message?.content||'');return normalizeItems(root.items,words.length)}catch(e){last=e}}
  throw last||new Error('Chưa cấu hình AI cho từ vựng')}
function normalizeItems(items,n){const out=Array(n).fill(null);for(const x of(Array.isArray(items)?items:[])){const i=Number(x.index);if(i<0||i>=n)continue;const item={ipaUS:String(x.ipaUS||'').trim(),ipaUK:String(x.ipaUK||'').trim(),meaningVi:String(x.meaningVi||'').trim(),partOfSpeech:String(x.partOfSpeech||'').trim(),exampleEn:String(x.exampleEn||'').trim(),exampleVi:String(x.exampleVi||'').trim()};if(item.meaningVi&&(item.ipaUS||item.ipaUK))out[i]=item}return out}
export async function generateSpeech(text,accent='US',voice='Kore',purpose='vocabulary'){const ttsModel=await loadSetting('ttsModel','gemini-3.1-flash-tts-preview');const lang=accent==='UK'?'en-GB':'en-US';const accentName=accent==='UK'?'British English':'American English';const prompt=purpose==='dialogue'?`Read only this dialogue line naturally in ${accentName}. Do not add or omit words. Text: ${text}`:`Pronounce only this English word or phrase clearly in ${accentName}, learner-friendly and natural. Do not add explanation. Text: ${text}`;const body={contents:[{parts:[{text:prompt}]}],generationConfig:{responseModalities:['AUDIO'],speechConfig:{languageCode:lang,voiceConfig:{prebuiltVoiceConfig:{voiceName:voice}}}}};const pool=await projectPool('speech');let last;for(const p of pool){try{const resp=await post(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(ttsModel)}:generateContent`,p.key,body,'gemini');return blobFromInline(geminiInline(resp))}catch(e){last=e;await markCooldown('speech',p.index,e);if(![429,500,502,503,504].includes(e.status))break;await sleep(250)}}throw last||new Error('Chưa cấu hình Gemini Speech Project Pool')}
export async function testAiConfig(){const p=await projectPool('vocab');if(!p.length)return 'Chưa có Gemini Vocabulary Project';return `Đã cấu hình ${p.length} Gemini Vocabulary Project`}
