import {openDb,getAll,addVocabBulk,updateVocab,getVocabByState,getAudio,putAudio,put,del,exportAll,restoreAll} from './db.js';
import {saveSecret,loadSecret,saveSetting,loadSetting} from './crypto.js';
import {parsePasted,parseFile,toVocabItems} from './importer.js';
import {enrichBatch,generateSpeech} from './ai.js';
import {playBlob,speakSystem} from './audio.js';
import {normalizeWord,shuffle,clamp,DAY,downloadBlob,fileStamp,toast,escapeHtml} from './utils.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let enrichmentRunning=false, stopEnrichment=false, learnWords=[],learnIndex=0,learnDetailMode=false,quizQuestions=[],quizIndex=0,quizCorrectCount=0,quizResults=[],quizCount=10,quizPool='WEAK',quizAnswered=false,currentDialogue=null,dialoguePlaying=false;
const audioGenerationInFlight=new Map();

await openDb();
await loadSettingsToUi();
await migrateVocabularyV11();
await refreshDashboard();
await refreshDialogues();
setupEvents();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
window.addEventListener('focus',()=>autoResumeEnrichment());
document.addEventListener('visibilitychange',()=>{if(!document.hidden)autoResumeEnrichment()});
setTimeout(autoResumeEnrichment,500);

function setupEvents(){
  $$('.nav-btn').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));
  $('#openImportBtn').onclick=()=>$('#importDialog').showModal(); $('#importNowBtn').onclick=importNow;
  $('#learn10Btn').onclick=startLearnSession; $('#closeLearnBtn').onclick=()=>$('#learnDialog').close();
  $('#quizBtn').onclick=openQuizSetup; $('#closeQuizBtn').onclick=()=>{resetQuizState();$('#quizDialog').close()};
  $('#openWordListBtn').onclick=()=>openWordList(); $('#closeWordListBtn').onclick=()=>$('#wordListDialog').close(); $('#wordSearch').oninput=()=>renderWordList($('#wordSearch').value); $('#wordList').onclick=e=>{const b=e.target.closest('[data-view-word]');if(b)openWordDetail(Number(b.dataset.viewWord))};
  $('.stats-grid').onclick=e=>{const b=e.target.closest('[data-filter]');if(b)openWordList(b.dataset.filter)};
  $('#saveSettingsBtn').onclick=saveSettingsFromUi;
  $$('.accent-setting').forEach(b=>b.onclick=()=>{$$('.accent-setting').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
  $('#quickResumeBtn').onclick=()=>runEnrichmentLoop(true);
  $('#exportDataBtn').onclick=exportBackup; $('#importDataBtn').onclick=()=>$('#restoreFileInput').click(); $('#restoreFileInput').onchange=restoreBackup;
  $('#exportConfigBtn').onclick=exportConfig; $('#importConfigBtn').onclick=()=>$('#configFileInput').click(); $('#configFileInput').onchange=importConfig;
  $('#newDialogueBtn').onclick=()=>openDialogueEditor(); $('#closeDialogueEditorBtn').onclick=()=>$('#dialogueEditor').close(); $('#saveDialogueBtn').onclick=saveDialogue; $('#playDialogueBtn').onclick=playDialogue;
  $('#dialogueRate').oninput=()=>$('#dialogueRateValue').textContent=`${Number($('#dialogueRate').value).toFixed(1)}×`;
}
function showScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${name}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));$('#screenTitle').textContent={vocab:'Từ vựng',listening:'Luyện nghe',settings:'Cài đặt'}[name]||''}

async function importNow(){try{const pasted=parsePasted($('#pasteWords').value);let fileWords=[];const file=$('#vocabFileInput').files[0];if(file)fileWords=await parseFile(file);const all=[...pasted,...fileWords];if(!all.length)throw new Error('Chưa có từ để import');const items=toVocabItems(all);const r=await addVocabBulk(items);$('#importPreview').classList.remove('hidden');$('#importPreview').innerHTML=`Đọc được: <b>${all.length.toLocaleString('vi-VN')}</b><br>Thêm mới: <b>${r.added.toLocaleString('vi-VN')}</b><br>Trùng bỏ qua: <b>${r.duplicates.toLocaleString('vi-VN')}</b>`;if(r.added){$('#pasteWords').value='';$('#vocabFileInput').value='';toast(`Đã thêm ${r.added} từ`);await refreshDashboard();runEnrichmentLoop(true)}else toast('Không có từ mới; nội dung được giữ lại để bạn kiểm tra.')}catch(e){toast(e.message||String(e))}}

async function autoResumeEnrichment(){const pending=(await getVocabByState('PENDING')).length;if(pending&&!enrichmentRunning&&document.visibilityState==='visible')runEnrichmentLoop(false)}
async function runEnrichmentLoop(userStarted=false){if(enrichmentRunning)return;enrichmentRunning=true;stopEnrichment=false;$('#quickResumeBtn').classList.add('hidden');setAiBadge('Đang xử lý','warn');try{while(!stopEnrichment&&document.visibilityState==='visible'){let pending=await getVocabByState('PENDING');if(!pending.length){const errors=await getVocabByState('ERROR');if(errors.length){for(const v of errors.filter(x=>(x.aiAttempts||0)<5).slice(0,25)){v.aiState='PENDING';await updateVocab(v)}pending=await getVocabByState('PENDING')}if(!pending.length)break}const batch=pending.slice(0,25);for(const v of batch){v.aiState='PROCESSING';v.aiAttempts=(v.aiAttempts||0)+1;await updateVocab(v)}try{const result=await enrichBatch(batch.map(x=>x.word));for(let i=0;i<batch.length;i++){const v=batch[i],d=result[i];if(d){Object.assign(v,d,{aiState:'READY',aiUpdatedAt:Date.now(),lastError:null})}else{v.aiState='ERROR';v.lastError='AI thiếu dữ liệu cho từ này'}await updateVocab(v)}}catch(e){for(const v of batch){v.aiState='PENDING';v.lastError=e.message||String(e);await updateVocab(v)}setAiBadge('Tạm dừng','danger');$('#quickResumeBtn').classList.remove('hidden');toast(`AI tạm dừng: ${String(e.message||e).slice(0,140)}`);break}await refreshDashboard();await new Promise(r=>setTimeout(r,150))}}finally{enrichmentRunning=false;await refreshDashboard();const pending=(await getVocabByState('PENDING')).length;if(pending){$('#quickResumeBtn').classList.remove('hidden');setAiBadge('Chờ tiếp tục','warn')}else setAiBadge('Sẵn sàng','ok')}}

async function refreshDashboard(){const all=await getAll('vocab');const ready=all.filter(v=>v.aiState==='READY').length,total=all.length,pct=total?Math.round(ready*100/total):0;$('#totalWords').textContent=total.toLocaleString('vi-VN');$('#aiPercent').textContent=`${pct}%`;$('#aiProgressBar').style.width=`${pct}%`;$('#aiRing').style.background=`conic-gradient(var(--primary) ${pct*3.6}deg,#e9edf7 0)`;$('#aiProgressText').textContent=`AI hoàn thiện: ${ready.toLocaleString('vi-VN')} / ${total.toLocaleString('vi-VN')}`;const s=stats(all);$('#statUnlearned').textContent=s.unlearned;$('#statLearning').textContent=s.learning;$('#statGood').textContent=s.good;$('#statMastered').textContent=s.mastered}
async function migrateVocabularyV11(){const done=await loadSetting('vocabSchemaV11Migrated',false);if(done)return;const all=await getAll('vocab');let changed=0;for(const v of all){if(v.aiState==='READY'&&(!Array.isArray(v.partsOfSpeech)||!Array.isArray(v.wordFamily))){v.aiState='PENDING';v.aiAttempts=0;v.lastError=null;await updateVocab(v);changed++}}await saveSetting('vocabSchemaV11Migrated',true);if(changed)toast(`Đang bổ sung dữ liệu mới cho ${changed} từ cũ. Tiến độ học được giữ nguyên.`)}
function stats(all){return{unlearned:all.filter(v=>!v.isLearned).length,learning:all.filter(v=>v.isLearned&&v.masteryScore<60).length,good:all.filter(v=>v.isLearned&&v.masteryScore>=60&&!isMastered(v)).length,mastered:all.filter(isMastered).length}}
function isMastered(v){return v.isLearned&&v.masteryScore>=80&&v.reviewCount>=5&&v.correctStreak>=2}
function setAiBadge(text,kind){const b=$('#aiStatusBadge');b.textContent=text;b.className=`badge ${kind}`}

async function chooseLearningTen(){const all=(await getAll('vocab')).filter(v=>v.aiState==='READY'&&!v.isLearned);if(!all.length)return[];return shuffle(all).slice(0,10)}
async function startLearnSession(){learnDetailMode=false;$('#learnDialogTitle').textContent='Học 10 từ';learnWords=await chooseLearningTen();if(!learnWords.length){const all=await getAll('vocab');const hasUnlearned=all.some(v=>!v.isLearned);toast(hasUnlearned?'Chưa có từ chưa học nào đã READY. Hãy để AI xử lý thêm.':'Không còn từ chưa học.');return}learnIndex=0;$('#learnDialog').showModal();renderLearn();prepareLearnAudio()}
function posHtml(v){const parts=Array.isArray(v.partsOfSpeech)&&v.partsOfSpeech.length?v.partsOfSpeech:[{type:v.partOfSpeech||'',meanings:[{vi:v.meaningVi||'',example:{en:v.exampleEn||'',vi:v.exampleVi||''}}]}];return parts.map(p=>`<section class="pos-block"><div class="pos-title">${escapeHtml(String(p.type||'').toUpperCase())}</div>${(p.meanings||[]).map((m,i)=>`<div class="sense"><b>${i+1}. ${escapeHtml(m.vi||'')}</b>${m.example?.en?`<div class="example"><span>${escapeHtml(m.example.en)}</span> <button class="mini-audio example-audio" data-text="${escapeHtml(m.example.en)}">🔊</button><br><span class="muted">${escapeHtml(m.example.vi||'')}</span></div>`:''}</div>`).join('')}</section>`).join('')}
function familyHtml(v){const fam=Array.isArray(v.wordFamily)?v.wordFamily:[];if(!fam.length)return'';return `<div class="word-family"><h3>WORD FAMILY</h3>${fam.map((f,i)=>`<details class="family-item"><summary><b>${escapeHtml(String(f.type||'').toUpperCase())}</b> · ${escapeHtml(f.word||'')}</summary><div class="family-body"><div class="ipa-row"><button class="audio-btn family-word-audio" data-index="${i}" data-accent="UK">🇬🇧 ${escapeHtml(f.pronunciation?.uk||'—')} 🔊</button><button class="audio-btn family-word-audio" data-index="${i}" data-accent="US">🇺🇸 ${escapeHtml(f.pronunciation?.us||'—')} 🔊</button></div><div class="meaning">${escapeHtml(f.meaningVi||'')}</div>${f.example?.en?`<div class="example"><span>${escapeHtml(f.example.en)}</span> <button class="mini-audio family-example-audio" data-index="${i}">🔊</button><br><span class="muted">${escapeHtml(f.example.vi||'')}</span></div>`:''}</div></details>`).join('')}</div>`}
function renderLearn(){const v=learnWords[learnIndex];if(!v){$('#learnContent').innerHTML='<div class="empty-state"><b>Hoàn thành phiên học.</b></div>';refreshDashboard();return}$('#learnContent').innerHTML=`<div class="learn-card">${learnDetailMode?'':`<div class="muted">${learnIndex+1} / ${learnWords.length}</div>`}<div class="learn-word">${escapeHtml(v.word)}</div><div class="ipa-row"><button id="playWordUK" class="audio-btn">🇬🇧 ${escapeHtml(v.ipaUK||'—')} 🔊</button><button id="playWordUS" class="audio-btn">🇺🇸 ${escapeHtml(v.ipaUS||'—')} 🔊</button></div>${posHtml(v)}${familyHtml(v)}${learnDetailMode?'<div class="detail-note muted">Chế độ xem chi tiết — không thay đổi tiến độ học.</div>':'<div class="learn-nav"><button id="dontKnowBtn" class="secondary">CHƯA NHỚ</button><button id="knowBtn" class="primary">ĐÃ NHỚ</button></div>'}</div>`;$('#playWordUK').onclick=()=>playTextCached(v.word,'UK',`vocab:${v.id}:UK`,v.id);$('#playWordUS').onclick=()=>playTextCached(v.word,'US',`vocab:${v.id}:US`,v.id);$$('.example-audio').forEach((b,i)=>b.onclick=()=>playTextCached(b.dataset.text,'US',`example:${v.id}:${i}:US`,v.id,true));$$('.family-word-audio').forEach(b=>b.onclick=()=>{const f=v.wordFamily[Number(b.dataset.index)];playTextCached(f.word,b.dataset.accent,`family:${v.id}:${normalizeWord(f.word)}:${b.dataset.accent}`,v.id)});$$('.family-example-audio').forEach(b=>{const i=Number(b.dataset.index),f=v.wordFamily[i];b.onclick=()=>playTextCached(f.example.en,'US',`family-example:${v.id}:${i}:US`,v.id,true)});if(!learnDetailMode){$('#dontKnowBtn').onclick=()=>gradeLearn(false);$('#knowBtn').onclick=()=>gradeLearn(true)}}
async function gradeLearn(correct){const v=learnWords[learnIndex];v.isLearned=true;v.reviewCount=(v.reviewCount||0)+1;v.lastReviewedAt=Date.now();if(correct){v.correctCount=(v.correctCount||0)+1;v.correctStreak=(v.correctStreak||0)+1;v.masteryScore=clamp((v.masteryScore||0)+12,0,100)}else{v.wrongCount=(v.wrongCount||0)+1;v.correctStreak=0;v.masteryScore=clamp((v.masteryScore||0)-8,0,100)}v.nextReviewAt=Date.now()+reviewInterval(v.masteryScore);await updateVocab(v);learnIndex++;renderLearn()}
function reviewInterval(score){return(score>=90?30:score>=80?14:score>=60?7:score>=30?3:1)*DAY}
function learnAudioJobsForWord(v){
  const jobs=[];
  for(const accent of ['UK','US'])jobs.push({text:v.word,accent,key:`vocab:${v.id}:${accent}`,wordId:v.id,isSentence:false});
  let exampleIndex=0;
  const parts=Array.isArray(v.partsOfSpeech)&&v.partsOfSpeech.length?v.partsOfSpeech:[{meanings:[{example:{en:v.exampleEn||''}}]}];
  for(const p of parts)for(const m of (p.meanings||[])){
    const text=String(m?.example?.en||'').trim();
    if(text)jobs.push({text,accent:'US',key:`example:${v.id}:${exampleIndex}:US`,wordId:v.id,isSentence:true});
    exampleIndex++;
  }
  const fam=Array.isArray(v.wordFamily)?v.wordFamily:[];
  fam.forEach((f,i)=>{
    const fw=String(f?.word||'').trim();
    if(fw)for(const accent of ['UK','US'])jobs.push({text:fw,accent,key:`family:${v.id}:${normalizeWord(fw)}:${accent}`,wordId:v.id,isSentence:false});
    const ex=String(f?.example?.en||'').trim();
    if(ex)jobs.push({text:ex,accent:'US',key:`family-example:${v.id}:${i}:US`,wordId:v.id,isSentence:true});
  });
  return jobs;
}
async function ensureAudioCached({text,accent,key,wordId,isSentence=false}){
  const cached=await getAudio(key);if(cached?.blob)return cached.blob;
  if(audioGenerationInFlight.has(key))return audioGenerationInFlight.get(key);
  const task=(async()=>{const voice=await loadSetting(accent==='UK'?'wordVoiceUK':'wordVoiceUS',await loadSetting('wordVoice','Kore'));const blob=await generateSpeech(text,accent,voice,isSentence?'dialogue':'vocabulary');await putAudio(key,blob,{wordId,accent,text});return blob})().finally(()=>audioGenerationInFlight.delete(key));
  audioGenerationInFlight.set(key,task);return task;
}
async function prepareLearnAudio(){
  if(!learnWords.length)return;
  $('#audioPrep').classList.remove('hidden');
  const priorityWords=[...learnWords.slice(0,2),...learnWords.slice(2)];
  const jobs=[];
  // Ưu tiên từ chính UK/US của từ đang xem và từ kế tiếp trước.
  for(const v of priorityWords.slice(0,2))for(const j of learnAudioJobsForWord(v).filter(x=>x.key.startsWith('vocab:')))jobs.push(j);
  // Sau đó chuẩn bị toàn bộ ví dụ + Word Family của 2 từ đầu.
  for(const v of priorityWords.slice(0,2))for(const j of learnAudioJobsForWord(v).filter(x=>!x.key.startsWith('vocab:')))jobs.push(j);
  // Cuối cùng prefetch đầy đủ các từ còn lại trong phiên.
  for(const v of priorityWords.slice(2))jobs.push(...learnAudioJobsForWord(v));
  let done=0,created=0,failed=0;
  $('#audioPrep').textContent=`Đang chuẩn bị audio AI cho phiên học 0/${jobs.length}… Bạn có thể học ngay.`;
  await runPool(jobs.map(j=>async()=>{const existed=!!(await getAudio(j.key))?.blob;if(!existed){try{await ensureAudioCached(j);created++}catch{failed++}}done++;$('#audioPrep').textContent=`Đang chuẩn bị audio AI ${done}/${jobs.length} • mới ${created}${failed?` • lỗi ${failed}`:''} — vẫn có thể học ngay.`}),2);
  $('#audioPrep').textContent=failed?`Prefetch hoàn tất: ${created} audio mới, ${failed} audio chưa tạo được. Khi bấm nghe app sẽ thử lại.`:`Audio AI của phiên học đã sẵn sàng (${jobs.length} mục, tạo mới ${created}).`;
}
async function playTextCached(text,accent,key,wordId,isSentence=false){let a=await getAudio(key);if(a?.blob){await playBlob(a.blob);return}try{const blob=await ensureAudioCached({text,accent,key,wordId,isSentence});await playBlob(blob)}catch{await speakSystem(text,accent,isSentence?1:0.9)}}
async function playWord(v,accent){return playTextCached(v.word,accent,`vocab:${v.id}:${accent}`,v.id)}

async function runPool(jobs,n){let i=0;async function w(){while(i<jobs.length){const j=i++;await jobs[j]()}}await Promise.all(Array.from({length:Math.min(n,jobs.length)},w))}

function resetQuizState(){quizQuestions=[];quizIndex=0;quizCorrectCount=0;quizResults=[];quizAnswered=false}
function quizPoolLabel(pool){return{WEAK:'Ôn từ yếu - ưu tiên từ điểm thấp, từng sai, lâu chưa ôn',LEARNED:'Từ đã học - ưu tiên từ lâu chưa kiểm tra',RANDOM:'Ngẫu nhiên trong các từ đã học',MASTERED:'Từ đã thuộc - kiểm tra lại để chống quên'}[pool]||pool}
function quizTypeTitle(type){return{EN_TO_VI:'Anh → Việt',VI_TO_EN:'Việt → Anh',LISTENING:'Nghe → gõ từ'}[type]||type}
function normalizeAnswerText(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
function quizReviewInterval(score){return(score<30?.5:score<60?1:score<80?3:7)*DAY}
async function openQuizSetup(){resetQuizState();quizCount=10;quizPool='WEAK';$('#quizDialog').showModal();await renderQuizSetup()}
async function renderQuizSetup(){const all=await getAll('vocab');const learnedReady=all.filter(v=>v.isLearned&&v.aiState==='READY'&&String(v.meaningVi||'').trim());$('#quizDialogTitle').textContent='Kiểm tra từ vựng';$('#quizContent').innerHTML=`<div class="quiz-setup"><div class="notice">Từ đã học có thể kiểm tra: <b>${learnedReady.length.toLocaleString('vi-VN')}</b><br>Bài test chạy local, không gọi AI. Chỉ kiểm tra các từ đã học.</div><h3>Số từ</h3><div class="quiz-counts">${[10,20,30].map(n=>`<button class="${quizCount===n?'primary':'ghost'} quiz-count" data-count="${n}">${n}</button>`).join('')}</div><h3>Nhóm kiểm tra</h3><div class="quiz-pools">${['WEAK','LEARNED','RANDOM','MASTERED'].map(p=>`<button class="${quizPool===p?'primary':'ghost'} quiz-pool" data-pool="${p}">${escapeHtml(quizPoolLabel(p))}</button>`).join('')}</div><div class="notice">3 dạng câu hỏi luân phiên: Anh → Việt (+10), Việt → Anh (+15), Nghe → gõ từ (+15). Trả lời sai: -10.<br>Đã thuộc khi ≥80%, đã test ít nhất 5 lần và đúng liên tiếp ít nhất 2 lần.</div><button id="beginQuizBtn" class="primary xl" ${learnedReady.length?'':'disabled'}>BẮT ĐẦU KIỂM TRA</button></div>`;$$('#quizContent .quiz-count').forEach(b=>b.onclick=async()=>{quizCount=Number(b.dataset.count);await renderQuizSetup()});$$('#quizContent .quiz-pool').forEach(b=>b.onclick=async()=>{quizPool=b.dataset.pool;await renderQuizSetup()});const begin=$('#beginQuizBtn');if(begin)begin.onclick=beginQuiz}
async function beginQuiz(){const all=await getAll('vocab');const readyLearned=all.filter(v=>v.isLearned&&v.aiState==='READY'&&String(v.meaningVi||'').trim());let candidates=[];if(quizPool==='WEAK'){const now=Date.now();candidates=[...readyLearned].sort((a,b)=>{const ad=(a.nextReviewAt==null||a.nextReviewAt<=now)?0:1,bd=(b.nextReviewAt==null||b.nextReviewAt<=now)?0:1;return ad-bd||(a.masteryScore||0)-(b.masteryScore||0)||(b.wrongCount||0)-(a.wrongCount||0)||(a.lastReviewedAt||0)-(b.lastReviewedAt||0)})}else if(quizPool==='LEARNED'){candidates=[...readyLearned].sort((a,b)=>(a.lastReviewedAt||0)-(b.lastReviewedAt||0))}else if(quizPool==='RANDOM'){candidates=shuffle([...readyLearned])}else if(quizPool==='MASTERED'){candidates=shuffle(readyLearned.filter(isMastered))}const selected=candidates.slice(0,Math.max(1,quizCount));if(!selected.length){toast(quizPool==='MASTERED'?'Chưa có từ nào đạt mức Đã thuộc để kiểm tra.':'Chưa có từ đã học và có dữ liệu AI để kiểm tra.');return}const optionPool=all.filter(v=>v.aiState==='READY'&&String(v.meaningVi||'').trim());const types=['EN_TO_VI','VI_TO_EN','LISTENING'];quizQuestions=selected.map((word,i)=>({word,type:types[i%types.length],options:types[i%types.length]==='EN_TO_VI'?buildMeaningOptions(word,optionPool):[]}));quizIndex=0;quizCorrectCount=0;quizResults=[];quizAnswered=false;if(selected.length<quizCount)toast(`Chỉ có ${selected.length} từ phù hợp để kiểm tra.`);await renderQuizQuestion()}
function buildMeaningOptions(correctWord,pool){const seen=new Set([normalizeAnswerText(correctWord.meaningVi)]),d=[];for(const x of shuffle(pool.filter(x=>x.id!==correctWord.id))){const m=String(x.meaningVi||'').trim(),k=normalizeAnswerText(m);if(!m||seen.has(k))continue;seen.add(k);d.push(m);if(d.length===3)break}return shuffle([...d,String(correctWord.meaningVi||'').trim()])}
async function renderQuizQuestion(){if(quizIndex>=quizQuestions.length){await renderQuizResult();return}const q=quizQuestions[quizIndex],v=q.word,accent=await loadSetting('accent','US'),ipa=accent==='UK'?(v.ipaUK||v.ipaUS):(v.ipaUS||v.ipaUK);$('#quizDialogTitle').textContent='Kiểm tra từ vựng';let body='';if(q.type==='EN_TO_VI'){body=`<div class="quiz-question">${escapeHtml(v.word)}</div>${ipa?`<div class="muted quiz-center">${escapeHtml(ipa)}</div>`:''}<div class="quiz-options">${q.options.map(o=>`<button class="quiz-option" data-answer="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div>`}else if(q.type==='VI_TO_EN'){body=`<div class="quiz-question">${escapeHtml(v.meaningVi)}</div><input id="quizTypedAnswer" class="quiz-input" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="Nhập từ/cụm từ tiếng Anh"><button id="quizSubmitBtn" class="primary xl">TRẢ LỜI</button>`}else{body=`<div class="quiz-question small">Nghe và gõ lại từ/cụm từ</div><button id="quizListenBtn" class="audio-btn quiz-listen">🔊 NGHE</button><input id="quizTypedAnswer" class="quiz-input" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="Bạn nghe được gì?"><button id="quizSubmitBtn" class="primary xl">TRẢ LỜI</button>`}$('#quizContent').innerHTML=`<div class="row between align-center"><span class="muted">Câu ${quizIndex+1}/${quizQuestions.length}</span><b>Đúng: ${quizCorrectCount}</b></div><div class="progress-line"><div style="width:${Math.round((quizIndex+1)*100/quizQuestions.length)}%"></div></div><div class="muted quiz-center">${escapeHtml(quizTypeTitle(q.type))}</div>${body}<div id="quizFeedback"></div><button id="quizNextBtn" class="primary xl hidden">${quizIndex===quizQuestions.length-1?'XEM KẾT QUẢ':'CÂU TIẾP THEO'}</button>`;if(q.type==='EN_TO_VI'){$$('#quizContent .quiz-option').forEach(b=>b.onclick=()=>submitQuizAnswer(b.dataset.answer,b))}else{const input=$('#quizTypedAnswer'),submit=$('#quizSubmitBtn');submit.onclick=()=>submitQuizAnswer(input.value,submit);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!quizAnswered)submit.click()});if(q.type==='LISTENING')$('#quizListenBtn').onclick=()=>playQuizWordLocal(v,accent)}$('#quizNextBtn').onclick=()=>{quizIndex++;quizAnswered=false;renderQuizQuestion()}}
async function playQuizWordLocal(v,accent){const key=`vocab:${v.id}:${accent}`,a=await getAudio(key);if(a?.blob)await playBlob(a.blob);else await speakSystem(v.word,accent,0.9)}
async function submitQuizAnswer(answer,sourceButton){if(quizAnswered)return;const q=quizQuestions[quizIndex];if(!q)return;const raw=String(answer||'').trim();if(!raw){toast('Hãy chọn hoặc nhập câu trả lời.');return}const v=q.word,before=v.masteryScore||0;const correct=q.type==='EN_TO_VI'?normalizeAnswerText(raw)===normalizeAnswerText(v.meaningVi):normalizeWord(raw)===v.normalizedWord;const delta=correct?(q.type==='EN_TO_VI'?10:15):-10;v.reviewCount=(v.reviewCount||0)+1;v.lastReviewedAt=Date.now();if(correct){quizCorrectCount++;v.correctCount=(v.correctCount||0)+1;v.correctStreak=(v.correctStreak||0)+1}else{v.wrongCount=(v.wrongCount||0)+1;v.correctStreak=0}v.masteryScore=clamp(before+delta,0,100);v.nextReviewAt=Date.now()+quizReviewInterval(v.masteryScore);await updateVocab(v);quizAnswered=true;quizResults.push({wordId:v.id,word:v.word,meaningVi:v.meaningVi,type:q.type,userAnswer:raw,correctAnswer:q.type==='EN_TO_VI'?v.meaningVi:v.word,correct,beforeMastery:before,afterMastery:v.masteryScore});if(q.type==='EN_TO_VI'){$$('#quizContent .quiz-option').forEach(b=>{b.disabled=true;if(normalizeAnswerText(b.dataset.answer)===normalizeAnswerText(v.meaningVi))b.classList.add('correct')});if(sourceButton&&!correct)sourceButton.classList.add('wrong')}else{const input=$('#quizTypedAnswer'),submit=$('#quizSubmitBtn');if(input)input.disabled=true;if(submit)submit.disabled=true;const listen=$('#quizListenBtn');if(listen)listen.disabled=false}const fb=$('#quizFeedback');fb.className=`quiz-feedback ${correct?'ok':'bad'}`;fb.textContent=correct?'✓ Chính xác':`✗ Chưa đúng. Đáp án: ${q.type==='EN_TO_VI'?v.meaningVi:v.word}`;$('#quizNextBtn').classList.remove('hidden')}
async function renderQuizResult(){await refreshDashboard();$('#quizDialogTitle').textContent='Kết quả kiểm tra';const total=quizQuestions.length,percent=total?Math.round(quizCorrectCount*100/total):0,wrong=quizResults.filter(r=>!r.correct);$('#quizContent').innerHTML=`<div class="quiz-result-head"><div class="big-number">${quizCorrectCount}/${total}</div><b>Điểm bài test: ${percent}%</b><div class="muted">Từ cần ôn lại: ${wrong.length}</div></div><h3>Chi tiết</h3><div class="quiz-result-list">${quizResults.map(r=>`<div class="quiz-result-row"><b>${r.correct?'✓':'✗'} ${escapeHtml(r.word)}</b><div class="muted">${escapeHtml(r.meaningVi||'')}</div>${r.correct?'':`<div class="muted">Bạn trả lời: ${escapeHtml(r.userAnswer)}<br>Đáp án: ${escapeHtml(r.correctAnswer)}</div>`}<div class="muted">Mức thuộc: ${r.beforeMastery}% → ${r.afterMastery}%</div></div>`).join('')}</div>${wrong.length?'<button id="retryWrongBtn" class="primary xl">KIỂM TRA LẠI TỪ SAI</button>':''}<button id="newQuizBtn" class="secondary xl">KIỂM TRA MỚI</button><button id="quizHomeBtn" class="ghost xl">VỀ TỪ VỰNG</button>`;if(wrong.length)$('#retryWrongBtn').onclick=retryWrongQuiz;$('#newQuizBtn').onclick=async()=>{resetQuizState();quizCount=10;quizPool='WEAK';await renderQuizSetup()};$('#quizHomeBtn').onclick=()=>{resetQuizState();$('#quizDialog').close()}}
async function retryWrongQuiz(){const wrongIds=new Set(quizResults.filter(r=>!r.correct).map(r=>r.wordId));if(!wrongIds.size){toast('Không có từ sai để kiểm tra lại.');return}const all=await getAll('vocab'),selected=all.filter(v=>wrongIds.has(v.id)&&v.isLearned&&v.aiState==='READY'&&String(v.meaningVi||'').trim()),optionPool=all.filter(v=>v.aiState==='READY'&&String(v.meaningVi||'').trim()),types=['EN_TO_VI','VI_TO_EN','LISTENING'];quizQuestions=selected.map((word,i)=>({word,type:types[i%types.length],options:types[i%types.length]==='EN_TO_VI'?buildMeaningOptions(word,optionPool):[]}));quizIndex=0;quizCorrectCount=0;quizResults=[];quizAnswered=false;await renderQuizQuestion()}

async function openWordList(filter='all'){$('#wordListDialog').showModal();$('#wordSearch').value='';$('#wordListDialog').dataset.filter=filter;await renderWordList('')}
async function renderWordList(q){const filter=$('#wordListDialog').dataset.filter||'all',n=normalizeWord(q);let all=await getAll('vocab');if(n)all=all.filter(v=>v.normalizedWord.includes(n)||normalizeWord(v.meaningVi).includes(n));if(filter==='unlearned')all=all.filter(v=>!v.isLearned);if(filter==='learning')all=all.filter(v=>v.isLearned&&v.masteryScore<60);if(filter==='good')all=all.filter(v=>v.isLearned&&v.masteryScore>=60&&!isMastered(v));if(filter==='mastered')all=all.filter(isMastered);all.sort((a,b)=>a.word.localeCompare(b.word));$('#wordList').innerHTML=all.slice(0,500).map(v=>`<div class="word-row"><div><b>${escapeHtml(v.word)}</b><br><small>${escapeHtml(v.meaningVi||'Đang chờ AI')}</small></div><div class="word-row-actions"><span class="badge ${v.aiState==='READY'?'ok':'neutral'}">${v.aiState==='READY'?`${v.masteryScore||0}%`:v.aiState}</span>${v.aiState==='READY'?`<button class="secondary compact view-word-btn" data-view-word="${v.id}">HỌC / XEM CHI TIẾT</button>`:''}</div></div>`).join('')+(all.length>500?`<div class="notice">Đang hiển thị 500/${all.length}. Hãy dùng ô tìm kiếm.</div>`:'')}

async function openWordDetail(id){const all=await getAll('vocab'),v=all.find(x=>x.id===id);if(!v){toast('Không tìm thấy từ này.');return}if(v.aiState!=='READY'){toast('Từ này chưa được AI xử lý xong.');return}learnDetailMode=true;learnWords=[v];learnIndex=0;$('#learnDialogTitle').textContent='Học / Xem chi tiết';$('#wordListDialog').close();$('#learnDialog').showModal();renderLearn()}

async function loadSettingsToUi(){const vals=await Promise.all([loadSecret('vocabKeys'),loadSecret('speechKeys'),loadSecret('groqKey'),loadSetting('groqEnabled',false),loadSetting('textModel','gemini-3.1-flash-lite'),loadSetting('ttsModel','gemini-3.1-flash-tts-preview'),loadSetting('groqModel','openai/gpt-oss-20b'),loadSetting('wordVoiceUK',await loadSetting('wordVoice','Kore')),loadSetting('wordVoiceUS',await loadSetting('wordVoice','Kore')),loadSetting('femaleVoice','Aoede'),loadSetting('maleVoice','Charon'),loadSetting('accent','US')]);[$('#vocabKeys').value,$('#speechKeys').value,$('#groqKey').value,$('#groqEnabled').checked,$('#textModel').value,$('#ttsModel').value,$('#groqModel').value,$('#wordVoiceUK').value,$('#wordVoiceUS').value,$('#femaleVoice').value,$('#maleVoice').value]=vals.slice(0,11);$$('.accent-setting').forEach(b=>b.classList.toggle('active',b.dataset.accent===vals[11]))}
async function saveSettingsFromUi(){await saveSecret('vocabKeys',$('#vocabKeys').value);await saveSecret('speechKeys',$('#speechKeys').value);await saveSecret('groqKey',$('#groqKey').value);await saveSetting('groqEnabled',$('#groqEnabled').checked);for(const id of ['textModel','ttsModel','groqModel','wordVoiceUK','wordVoiceUS','femaleVoice','maleVoice'])await saveSetting(id,$(`#${id}`).value.trim());await saveSetting('accent',$('.accent-setting.active')?.dataset.accent||'US');toast('Đã lưu cài đặt');autoResumeEnrichment()}

async function exportBackup(){const data=await exportAll();downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`EnglishStudy_Backup_${fileStamp()}.json`)}
async function restoreBackup(){const f=$('#restoreFileInput').files[0];if(!f)return;try{await restoreAll(JSON.parse(await f.text()));await refreshDashboard();await refreshDialogues();toast('Khôi phục dữ liệu thành công')}catch(e){toast(e.message)}finally{$('#restoreFileInput').value=''}}
async function exportConfig(){const config={version:1,vocabKeys:await loadSecret('vocabKeys'),speechKeys:await loadSecret('speechKeys'),groqKey:await loadSecret('groqKey'),groqEnabled:await loadSetting('groqEnabled',false),textModel:await loadSetting('textModel',''),ttsModel:await loadSetting('ttsModel',''),groqModel:await loadSetting('groqModel',''),wordVoiceUK:await loadSetting('wordVoiceUK',await loadSetting('wordVoice','Kore')),wordVoiceUS:await loadSetting('wordVoiceUS',await loadSetting('wordVoice','Kore')),femaleVoice:await loadSetting('femaleVoice','Aoede'),maleVoice:await loadSetting('maleVoice','Charon'),accent:await loadSetting('accent','US')};downloadBlob(new Blob([JSON.stringify(config,null,2)],{type:'application/json'}),`EnglishStudy_AI_Config_${fileStamp()}.json`);toast('File cấu hình chứa API key. Hãy giữ kín.')}
async function importConfig(){const f=$('#configFileInput').files[0];if(!f)return;try{const c=JSON.parse(await f.text());await saveSecret('vocabKeys',c.vocabKeys||'');await saveSecret('speechKeys',c.speechKeys||'');await saveSecret('groqKey',c.groqKey||'');if(c.wordVoice&&!c.wordVoiceUK)await saveSetting('wordVoiceUK',c.wordVoice);if(c.wordVoice&&!c.wordVoiceUS)await saveSetting('wordVoiceUS',c.wordVoice);for(const k of ['groqEnabled','textModel','ttsModel','groqModel','wordVoiceUK','wordVoiceUS','femaleVoice','maleVoice','accent'])if(c[k]!==undefined)await saveSetting(k,c[k]);await loadSettingsToUi();toast('Đã nhập cấu hình AI')}catch(e){toast('File cấu hình không hợp lệ')}finally{$('#configFileInput').value=''}}

function parseDialogue(text){const speakers=new Map();let nextGender='female';return String(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const i=line.indexOf(':');const speaker=i>0?line.slice(0,i).trim():'Speaker',content=i>0?line.slice(i+1).trim():line;const key=speaker.toLowerCase();let gender;if(/^(w|woman|female|f)$/i.test(speaker))gender='female';else if(/^(m|man|male)$/i.test(speaker))gender='male';else if(speakers.has(key))gender=speakers.get(key);else{gender=nextGender;nextGender=nextGender==='female'?'male':'female';speakers.set(key,gender)}return{speaker,text:content,gender}})}
function openDialogueEditor(d=null){currentDialogue=d?structuredClone(d):{id:crypto.randomUUID(),title:'',text:'',rate:1,createdAt:Date.now()};$('#dialogueEditorTitle').textContent=d?'Đoạn nghe':'Tạo đoạn nghe mới';$('#dialogueTitle').value=currentDialogue.title||'';$('#dialogueText').value=currentDialogue.text||'';$('#dialogueRate').value=currentDialogue.rate||1;$('#dialogueRateValue').textContent=`${Number($('#dialogueRate').value).toFixed(1)}×`;renderDialogueLines();$('#dialogueEditor').showModal()}
function renderDialogueLines(active=-1){const lines=parseDialogue($('#dialogueText').value);$('#dialoguePlayerLines').innerHTML=lines.map((l,i)=>`<div class="dialogue-line ${i===active?'active':''}"><b>${escapeHtml(l.speaker)}:</b> ${escapeHtml(l.text)}</div>`).join('')}
async function saveDialogue(){if(!currentDialogue)return;currentDialogue.title=$('#dialogueTitle').value.trim()||'Đoạn nghe';currentDialogue.text=$('#dialogueText').value.trim();currentDialogue.rate=Number($('#dialogueRate').value)||1;if(!currentDialogue.text){toast('Hãy nhập nội dung hội thoại');return}await put('dialogues',currentDialogue);await refreshDialogues();toast('Đã lưu đoạn nghe')}
async function refreshDialogues(){const all=(await getAll('dialogues')).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('#dialogueEmpty').classList.toggle('hidden',all.length>0);$('#dialogueList').innerHTML=all.map(d=>`<div class="dialogue-item" data-id="${d.id}"><h3>${escapeHtml(d.title)}</h3><div class="muted">${parseDialogue(d.text).length} lượt thoại</div><div class="row small-gap" style="margin-top:10px"><button class="secondary compact open-d">MỞ</button><button class="ghost compact delete-d">XÓA</button></div></div>`).join('');$$('.open-d').forEach(b=>b.onclick=async()=>{const id=b.closest('.dialogue-item').dataset.id;openDialogueEditor((await getAll('dialogues')).find(x=>x.id===id))});$$('.delete-d').forEach(b=>b.onclick=async()=>{const id=b.closest('.dialogue-item').dataset.id;await del('dialogues',id);refreshDialogues()})}
async function playDialogue(){if(dialoguePlaying)return;await saveDialogue();const lines=parseDialogue($('#dialogueText').value);if(!lines.length)return;dialoguePlaying=true;$('#playDialogueBtn').textContent='Đang chuẩn bị...';$('#dialoguePrep').classList.remove('hidden');const accent=await loadSetting('accent','US'),female=await loadSetting('femaleVoice','Aoede'),male=await loadSetting('maleVoice','Charon'),rate=Number($('#dialogueRate').value)||1;const prepared=Array(lines.length).fill(null);let done=0;await runPool(lines.map((l,i)=>async()=>{const key=`dialogue:${currentDialogue.id}:${i}:${accent}:${normalizeWord(l.text)}`;let a=await getAudio(key);if(!a?.blob){try{const blob=await generateSpeech(l.text,accent,l.gender==='female'?female:male,'dialogue');await putAudio(key,blob,{dialogueId:currentDialogue.id,line:i,accent});a={blob}}catch{a=null}}prepared[i]=a?.blob||null;done++;$('#dialoguePrep').textContent=`Chuẩn bị giọng ${done}/${lines.length}`}),2);$('#playDialogueBtn').textContent='■ ĐANG PHÁT';for(let i=0;i<lines.length&&dialoguePlaying;i++){renderDialogueLines(i);if(prepared[i])await playBlob(prepared[i],rate);else await speakSystem(lines[i].text,accent,rate,lines[i].gender)}renderDialogueLines();dialoguePlaying=false;$('#playDialogueBtn').textContent='▶ PHÁT';$('#dialoguePrep').textContent='Đã lưu audio AI tạo được vào máy.'}

$('#dialogueText').addEventListener('input',()=>renderDialogueLines());
