import {openDb,getAll,addVocabBulk,updateVocab,getVocabByState,getAudio,putAudio,put,del,exportAll,restoreAll} from './db.js';
import {saveSecret,loadSecret,saveSetting,loadSetting} from './crypto.js';
import {parsePasted,parseFile,toVocabItems} from './importer.js';
import {enrichBatch,generateSpeech} from './ai.js';
import {playBlob,speakSystem} from './audio.js';
import {normalizeWord,shuffle,clamp,DAY,downloadBlob,fileStamp,toast,escapeHtml} from './utils.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let enrichmentRunning=false, stopEnrichment=false, learnWords=[],learnIndex=0,learnAccent='US',quizWords=[],quizIndex=0,quizScore=0,currentDialogue=null,dialoguePlaying=false;

await openDb();
await loadSettingsToUi();
await refreshDashboard();
await refreshDialogues();
setupEvents();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
window.addEventListener('focus',()=>autoResumeEnrichment());
document.addEventListener('visibilitychange',()=>{if(!document.hidden)autoResumeEnrichment()});
setTimeout(autoResumeEnrichment,500);

function setupEvents(){
  $$('.nav-btn').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));
  $('#openImportBtn').onclick=()=>$('#importDialog').showModal(); $('#importNowBtn').onclick=importNow;
  $('#learn10Btn').onclick=startLearnSession; $('#closeLearnBtn').onclick=()=>$('#learnDialog').close();
  $$('.accent-btn').forEach(b=>b.onclick=()=>{$$('.accent-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');learnAccent=b.dataset.accent;prepareLearnAudio()});
  $('#quizBtn').onclick=startQuiz; $('#closeQuizBtn').onclick=()=>$('#quizDialog').close();
  $('#openWordListBtn').onclick=()=>openWordList(); $('#closeWordListBtn').onclick=()=>$('#wordListDialog').close(); $('#wordSearch').oninput=()=>renderWordList($('#wordSearch').value);
  $('.stats-grid').onclick=e=>{const b=e.target.closest('[data-filter]');if(b)openWordList(b.dataset.filter)};
  $('#saveSettingsBtn').onclick=saveSettingsFromUi;
  $$('.accent-setting').forEach(b=>b.onclick=()=>{$$('.accent-setting').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
  $('#quickResumeBtn').onclick=()=>runEnrichmentLoop(true);
  $('#exportDataBtn').onclick=exportBackup; $('#importDataBtn').onclick=()=>$('#restoreFileInput').click(); $('#restoreFileInput').onchange=restoreBackup;
  $('#exportConfigBtn').onclick=exportConfig; $('#importConfigBtn').onclick=()=>$('#configFileInput').click(); $('#configFileInput').onchange=importConfig;
  $('#newDialogueBtn').onclick=()=>openDialogueEditor(); $('#closeDialogueEditorBtn').onclick=()=>$('#dialogueEditor').close(); $('#saveDialogueBtn').onclick=saveDialogue; $('#playDialogueBtn').onclick=playDialogue;
  $('#dialogueRate').oninput=()=>$('#dialogueRateValue').textContent=`${Number($('#dialogueRate').value).toFixed(1)}×`;
}
function showScreen(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${name}`));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));$('#screenTitle').textContent={vocab:'Từ vựng',listening:'Luyện nghe',settings:'Cài đặt'}[name]||''}

async function importNow(){try{const pasted=parsePasted($('#pasteWords').value);let fileWords=[];const file=$('#vocabFileInput').files[0];if(file)fileWords=await parseFile(file);const all=[...pasted,...fileWords];if(!all.length)throw new Error('Chưa có từ để import');const items=toVocabItems(all);const r=await addVocabBulk(items);$('#importPreview').classList.remove('hidden');$('#importPreview').innerHTML=`Đọc được: <b>${all.length.toLocaleString('vi-VN')}</b><br>Thêm mới: <b>${r.added.toLocaleString('vi-VN')}</b><br>Trùng bỏ qua: <b>${r.duplicates.toLocaleString('vi-VN')}</b>`;if(r.added){$('#pasteWords').value='';$('#vocabFileInput').value='';toast(`Đã thêm ${r.added} từ`);await refreshDashboard();runEnrichmentLoop(true)}else toast('Không có từ mới; nội dung được giữ lại để bạn kiểm tra.')}catch(e){toast(e.message||String(e))}}

async function autoResumeEnrichment(){const pending=(await getVocabByState('PENDING')).length;if(pending&&!enrichmentRunning&&document.visibilityState==='visible')runEnrichmentLoop(false)}
async function runEnrichmentLoop(userStarted=false){if(enrichmentRunning)return;enrichmentRunning=true;stopEnrichment=false;$('#quickResumeBtn').classList.add('hidden');setAiBadge('Đang xử lý','warn');try{while(!stopEnrichment&&document.visibilityState==='visible'){let pending=await getVocabByState('PENDING');if(!pending.length){const errors=await getVocabByState('ERROR');if(errors.length){for(const v of errors.filter(x=>(x.aiAttempts||0)<5).slice(0,25)){v.aiState='PENDING';await updateVocab(v)}pending=await getVocabByState('PENDING')}if(!pending.length)break}const batch=pending.slice(0,25);for(const v of batch){v.aiState='PROCESSING';v.aiAttempts=(v.aiAttempts||0)+1;await updateVocab(v)}try{const result=await enrichBatch(batch.map(x=>x.word));for(let i=0;i<batch.length;i++){const v=batch[i],d=result[i];if(d){Object.assign(v,d,{aiState:'READY',aiUpdatedAt:Date.now(),lastError:null})}else{v.aiState='ERROR';v.lastError='AI thiếu dữ liệu cho từ này'}await updateVocab(v)}}catch(e){for(const v of batch){v.aiState='PENDING';v.lastError=e.message||String(e);await updateVocab(v)}setAiBadge('Tạm dừng','danger');$('#quickResumeBtn').classList.remove('hidden');toast(`AI tạm dừng: ${String(e.message||e).slice(0,140)}`);break}await refreshDashboard();await new Promise(r=>setTimeout(r,150))}}finally{enrichmentRunning=false;await refreshDashboard();const pending=(await getVocabByState('PENDING')).length;if(pending){$('#quickResumeBtn').classList.remove('hidden');setAiBadge('Chờ tiếp tục','warn')}else setAiBadge('Sẵn sàng','ok')}}

async function refreshDashboard(){const all=await getAll('vocab');const ready=all.filter(v=>v.aiState==='READY').length,total=all.length,pct=total?Math.round(ready*100/total):0;$('#totalWords').textContent=total.toLocaleString('vi-VN');$('#aiPercent').textContent=`${pct}%`;$('#aiProgressBar').style.width=`${pct}%`;$('#aiRing').style.background=`conic-gradient(var(--primary) ${pct*3.6}deg,#e9edf7 0)`;$('#aiProgressText').textContent=`AI hoàn thiện: ${ready.toLocaleString('vi-VN')} / ${total.toLocaleString('vi-VN')}`;const s=stats(all);$('#statUnlearned').textContent=s.unlearned;$('#statLearning').textContent=s.learning;$('#statGood').textContent=s.good;$('#statMastered').textContent=s.mastered}
function stats(all){return{unlearned:all.filter(v=>!v.isLearned).length,learning:all.filter(v=>v.isLearned&&v.masteryScore<60).length,good:all.filter(v=>v.isLearned&&v.masteryScore>=60&&!isMastered(v)).length,mastered:all.filter(isMastered).length}}
function isMastered(v){return v.isLearned&&v.masteryScore>=80&&v.reviewCount>=5&&v.correctStreak>=2}
function setAiBadge(text,kind){const b=$('#aiStatusBadge');b.textContent=text;b.className=`badge ${kind}`}

async function chooseTen(){const all=(await getAll('vocab')).filter(v=>v.aiState==='READY');if(!all.length)return[];const due=all.filter(v=>v.isLearned&&(!v.nextReviewAt||v.nextReviewAt<=Date.now())).sort((a,b)=>(a.masteryScore||0)-(b.masteryScore||0));const fresh=shuffle(all.filter(v=>!v.isLearned));const chosen=[];for(const v of [...due,...fresh])if(chosen.length<10&&!chosen.some(x=>x.id===v.id))chosen.push(v);if(chosen.length<10)for(const v of shuffle(all))if(chosen.length<10&&!chosen.some(x=>x.id===v.id))chosen.push(v);return chosen}
async function startLearnSession(){learnWords=await chooseTen();if(!learnWords.length){toast('Chưa có từ READY. Hãy import và để AI xử lý trước.');return}learnIndex=0;learnAccent=await loadSetting('accent','US');$$('.accent-btn').forEach(b=>b.classList.toggle('active',b.dataset.accent===learnAccent));$('#learnDialog').showModal();renderLearn();prepareLearnAudio()}
function renderLearn(){const v=learnWords[learnIndex];if(!v){$('#learnContent').innerHTML='<div class="empty-state"><b>Hoàn thành phiên học.</b></div>';refreshDashboard();return}$('#learnContent').innerHTML=`<div class="learn-card"><div class="muted">${learnIndex+1} / ${learnWords.length}</div><div class="learn-word">${escapeHtml(v.word)}</div><div class="ipa-row"><span>🇺🇸 ${escapeHtml(v.ipaUS||'—')}</span><span>🇬🇧 ${escapeHtml(v.ipaUK||'—')}</span></div><div class="meaning">${escapeHtml(v.meaningVi)}</div><div class="muted">${escapeHtml(v.partOfSpeech)}</div><div class="example"><b>${escapeHtml(v.exampleEn)}</b><br><span class="muted">${escapeHtml(v.exampleVi||'')}</span></div><p><button id="playWordBtn" class="audio-btn">🔊 ${learnAccent}</button></p><div class="learn-nav"><button id="dontKnowBtn" class="secondary">CHƯA NHỚ</button><button id="knowBtn" class="primary">ĐÃ NHỚ</button></div></div>`;$('#playWordBtn').onclick=()=>playWord(v,learnAccent);$('#dontKnowBtn').onclick=()=>gradeLearn(false);$('#knowBtn').onclick=()=>gradeLearn(true)}
async function gradeLearn(correct){const v=learnWords[learnIndex];v.isLearned=true;v.reviewCount=(v.reviewCount||0)+1;v.lastReviewedAt=Date.now();if(correct){v.correctCount=(v.correctCount||0)+1;v.correctStreak=(v.correctStreak||0)+1;v.masteryScore=clamp((v.masteryScore||0)+12,0,100)}else{v.wrongCount=(v.wrongCount||0)+1;v.correctStreak=0;v.masteryScore=clamp((v.masteryScore||0)-8,0,100)}v.nextReviewAt=Date.now()+reviewInterval(v.masteryScore);await updateVocab(v);learnIndex++;renderLearn()}
function reviewInterval(score){return(score>=90?30:score>=80?14:score>=60?7:score>=30?3:1)*DAY}
async function prepareLearnAudio(){if(!learnWords.length)return;$('#audioPrep').classList.remove('hidden');let done=0,created=0;const voice=await loadSetting('wordVoice','Kore');const jobs=learnWords.map(v=>async()=>{const key=`vocab:${v.id}:${learnAccent}`;if(!(await getAudio(key))){try{const blob=await generateSpeech(v.word,learnAccent,voice,'vocabulary');await putAudio(key,blob,{wordId:v.id,accent:learnAccent});created++}catch{} }done++;$('#audioPrep').textContent=`Chuẩn bị phát âm ${done}/${learnWords.length} • tạo mới ${created}`});await runPool(jobs,2);$('#audioPrep').textContent=`Sẵn sàng audio ${learnAccent}. Nếu AI TTS không khả dụng, app dùng giọng hệ thống iPhone.`}
async function playWord(v,accent){const key=`vocab:${v.id}:${accent}`,a=await getAudio(key);if(a?.blob){await playBlob(a.blob);return}try{const voice=await loadSetting('wordVoice','Kore');const blob=await generateSpeech(v.word,accent,voice,'vocabulary');await putAudio(key,blob,{wordId:v.id,accent});await playBlob(blob)}catch{await speakSystem(v.word,accent,0.9)}}
async function runPool(jobs,n){let i=0;async function w(){while(i<jobs.length){const j=i++;await jobs[j]()}}await Promise.all(Array.from({length:Math.min(n,jobs.length)},w))}

async function startQuiz(){quizWords=await chooseTen();if(!quizWords.length){toast('Chưa có từ READY');return}quizIndex=0;quizScore=0;$('#quizDialog').showModal();renderQuiz()}
async function renderQuiz(){if(quizIndex>=quizWords.length){$('#quizContent').innerHTML=`<div class="empty-state"><div class="big-number">${quizScore}/${quizWords.length}</div><b>Hoàn thành bài kiểm tra</b></div>`;await refreshDashboard();return}const v=quizWords[quizIndex],all=(await getAll('vocab')).filter(x=>x.aiState==='READY'&&x.id!==v.id);const opts=shuffle([v,...shuffle(all).slice(0,3)]);$('#quizContent').innerHTML=`<div class="muted">Câu ${quizIndex+1}/${quizWords.length}</div><div class="quiz-question">${escapeHtml(v.word)}</div><div class="quiz-options">${opts.map(x=>`<button class="quiz-option" data-id="${x.id}">${escapeHtml(x.meaningVi)}</button>`).join('')}</div>`;$$('#quizContent .quiz-option').forEach(b=>b.onclick=()=>answerQuiz(v,Number(b.dataset.id),b))}
async function answerQuiz(v,id,btn){const correct=id===v.id;$$('#quizContent .quiz-option').forEach(b=>b.disabled=true);btn.classList.add(correct?'correct':'wrong');if(!correct){const c=$(`#quizContent .quiz-option[data-id="${v.id}"]`);c?.classList.add('correct')}v.isLearned=true;v.reviewCount=(v.reviewCount||0)+1;v.lastReviewedAt=Date.now();if(correct){quizScore++;v.correctCount=(v.correctCount||0)+1;v.correctStreak=(v.correctStreak||0)+1;v.masteryScore=clamp((v.masteryScore||0)+15,0,100)}else{v.wrongCount=(v.wrongCount||0)+1;v.correctStreak=0;v.masteryScore=clamp((v.masteryScore||0)-10,0,100)}v.nextReviewAt=Date.now()+reviewInterval(v.masteryScore);await updateVocab(v);setTimeout(()=>{quizIndex++;renderQuiz()},650)}

async function openWordList(filter='all'){$('#wordListDialog').showModal();$('#wordSearch').value='';$('#wordListDialog').dataset.filter=filter;await renderWordList('')}
async function renderWordList(q){const filter=$('#wordListDialog').dataset.filter||'all',n=normalizeWord(q);let all=await getAll('vocab');if(n)all=all.filter(v=>v.normalizedWord.includes(n)||normalizeWord(v.meaningVi).includes(n));if(filter==='unlearned')all=all.filter(v=>!v.isLearned);if(filter==='learning')all=all.filter(v=>v.isLearned&&v.masteryScore<60);if(filter==='good')all=all.filter(v=>v.isLearned&&v.masteryScore>=60&&!isMastered(v));if(filter==='mastered')all=all.filter(isMastered);all.sort((a,b)=>a.word.localeCompare(b.word));$('#wordList').innerHTML=all.slice(0,500).map(v=>`<div class="word-row"><div><b>${escapeHtml(v.word)}</b><br><small>${escapeHtml(v.meaningVi||'Đang chờ AI')}</small></div><span class="badge ${v.aiState==='READY'?'ok':'neutral'}">${v.aiState==='READY'?`${v.masteryScore||0}%`:v.aiState}</span></div>`).join('')+(all.length>500?`<div class="notice">Đang hiển thị 500/${all.length}. Hãy dùng ô tìm kiếm.</div>`:'')}

async function loadSettingsToUi(){const vals=await Promise.all([loadSecret('vocabKeys'),loadSecret('speechKeys'),loadSecret('groqKey'),loadSetting('groqEnabled',false),loadSetting('textModel','gemini-3.1-flash-lite'),loadSetting('ttsModel','gemini-3.1-flash-tts-preview'),loadSetting('groqModel','openai/gpt-oss-20b'),loadSetting('wordVoice','Kore'),loadSetting('femaleVoice','Aoede'),loadSetting('maleVoice','Charon'),loadSetting('accent','US')]);[$('#vocabKeys').value,$('#speechKeys').value,$('#groqKey').value,$('#groqEnabled').checked,$('#textModel').value,$('#ttsModel').value,$('#groqModel').value,$('#wordVoice').value,$('#femaleVoice').value,$('#maleVoice').value]=vals.slice(0,10);$$('.accent-setting').forEach(b=>b.classList.toggle('active',b.dataset.accent===vals[10]))}
async function saveSettingsFromUi(){await saveSecret('vocabKeys',$('#vocabKeys').value);await saveSecret('speechKeys',$('#speechKeys').value);await saveSecret('groqKey',$('#groqKey').value);await saveSetting('groqEnabled',$('#groqEnabled').checked);for(const id of ['textModel','ttsModel','groqModel','wordVoice','femaleVoice','maleVoice'])await saveSetting(id,$(`#${id}`).value.trim());await saveSetting('accent',$('.accent-setting.active')?.dataset.accent||'US');toast('Đã lưu cài đặt');autoResumeEnrichment()}

async function exportBackup(){const data=await exportAll();downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`EnglishStudy_Backup_${fileStamp()}.json`)}
async function restoreBackup(){const f=$('#restoreFileInput').files[0];if(!f)return;try{await restoreAll(JSON.parse(await f.text()));await refreshDashboard();await refreshDialogues();toast('Khôi phục dữ liệu thành công')}catch(e){toast(e.message)}finally{$('#restoreFileInput').value=''}}
async function exportConfig(){const config={version:1,vocabKeys:await loadSecret('vocabKeys'),speechKeys:await loadSecret('speechKeys'),groqKey:await loadSecret('groqKey'),groqEnabled:await loadSetting('groqEnabled',false),textModel:await loadSetting('textModel',''),ttsModel:await loadSetting('ttsModel',''),groqModel:await loadSetting('groqModel',''),wordVoice:await loadSetting('wordVoice','Kore'),femaleVoice:await loadSetting('femaleVoice','Aoede'),maleVoice:await loadSetting('maleVoice','Charon'),accent:await loadSetting('accent','US')};downloadBlob(new Blob([JSON.stringify(config,null,2)],{type:'application/json'}),`EnglishStudy_AI_Config_${fileStamp()}.json`);toast('File cấu hình chứa API key. Hãy giữ kín.')}
async function importConfig(){const f=$('#configFileInput').files[0];if(!f)return;try{const c=JSON.parse(await f.text());await saveSecret('vocabKeys',c.vocabKeys||'');await saveSecret('speechKeys',c.speechKeys||'');await saveSecret('groqKey',c.groqKey||'');for(const k of ['groqEnabled','textModel','ttsModel','groqModel','wordVoice','femaleVoice','maleVoice','accent'])if(c[k]!==undefined)await saveSetting(k,c[k]);await loadSettingsToUi();toast('Đã nhập cấu hình AI')}catch(e){toast('File cấu hình không hợp lệ')}finally{$('#configFileInput').value=''}}

function parseDialogue(text){const speakers=new Map();let nextGender='female';return String(text).split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const i=line.indexOf(':');const speaker=i>0?line.slice(0,i).trim():'Speaker',content=i>0?line.slice(i+1).trim():line;const key=speaker.toLowerCase();let gender;if(/^(w|woman|female|f)$/i.test(speaker))gender='female';else if(/^(m|man|male)$/i.test(speaker))gender='male';else if(speakers.has(key))gender=speakers.get(key);else{gender=nextGender;nextGender=nextGender==='female'?'male':'female';speakers.set(key,gender)}return{speaker,text:content,gender}})}
function openDialogueEditor(d=null){currentDialogue=d?structuredClone(d):{id:crypto.randomUUID(),title:'',text:'',rate:1,createdAt:Date.now()};$('#dialogueEditorTitle').textContent=d?'Đoạn nghe':'Tạo đoạn nghe mới';$('#dialogueTitle').value=currentDialogue.title||'';$('#dialogueText').value=currentDialogue.text||'';$('#dialogueRate').value=currentDialogue.rate||1;$('#dialogueRateValue').textContent=`${Number($('#dialogueRate').value).toFixed(1)}×`;renderDialogueLines();$('#dialogueEditor').showModal()}
function renderDialogueLines(active=-1){const lines=parseDialogue($('#dialogueText').value);$('#dialoguePlayerLines').innerHTML=lines.map((l,i)=>`<div class="dialogue-line ${i===active?'active':''}"><b>${escapeHtml(l.speaker)}:</b> ${escapeHtml(l.text)}</div>`).join('')}
async function saveDialogue(){if(!currentDialogue)return;currentDialogue.title=$('#dialogueTitle').value.trim()||'Đoạn nghe';currentDialogue.text=$('#dialogueText').value.trim();currentDialogue.rate=Number($('#dialogueRate').value)||1;if(!currentDialogue.text){toast('Hãy nhập nội dung hội thoại');return}await put('dialogues',currentDialogue);await refreshDialogues();toast('Đã lưu đoạn nghe')}
async function refreshDialogues(){const all=(await getAll('dialogues')).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));$('#dialogueEmpty').classList.toggle('hidden',all.length>0);$('#dialogueList').innerHTML=all.map(d=>`<div class="dialogue-item" data-id="${d.id}"><h3>${escapeHtml(d.title)}</h3><div class="muted">${parseDialogue(d.text).length} lượt thoại</div><div class="row small-gap" style="margin-top:10px"><button class="secondary compact open-d">MỞ</button><button class="ghost compact delete-d">XÓA</button></div></div>`).join('');$$('.open-d').forEach(b=>b.onclick=async()=>{const id=b.closest('.dialogue-item').dataset.id;openDialogueEditor((await getAll('dialogues')).find(x=>x.id===id))});$$('.delete-d').forEach(b=>b.onclick=async()=>{const id=b.closest('.dialogue-item').dataset.id;await del('dialogues',id);refreshDialogues()})}
async function playDialogue(){if(dialoguePlaying)return;await saveDialogue();const lines=parseDialogue($('#dialogueText').value);if(!lines.length)return;dialoguePlaying=true;$('#playDialogueBtn').textContent='Đang chuẩn bị...';$('#dialoguePrep').classList.remove('hidden');const accent=await loadSetting('accent','US'),female=await loadSetting('femaleVoice','Aoede'),male=await loadSetting('maleVoice','Charon'),rate=Number($('#dialogueRate').value)||1;const prepared=Array(lines.length).fill(null);let done=0;await runPool(lines.map((l,i)=>async()=>{const key=`dialogue:${currentDialogue.id}:${i}:${accent}:${normalizeWord(l.text)}`;let a=await getAudio(key);if(!a?.blob){try{const blob=await generateSpeech(l.text,accent,l.gender==='female'?female:male,'dialogue');await putAudio(key,blob,{dialogueId:currentDialogue.id,line:i,accent});a={blob}}catch{a=null}}prepared[i]=a?.blob||null;done++;$('#dialoguePrep').textContent=`Chuẩn bị giọng ${done}/${lines.length}`}),2);$('#playDialogueBtn').textContent='■ ĐANG PHÁT';for(let i=0;i<lines.length&&dialoguePlaying;i++){renderDialogueLines(i);if(prepared[i])await playBlob(prepared[i],rate);else await speakSystem(lines[i].text,accent,rate,lines[i].gender)}renderDialogueLines();dialoguePlaying=false;$('#playDialogueBtn').textContent='▶ PHÁT';$('#dialoguePrep').textContent='Đã lưu audio AI tạo được vào máy.'}

$('#dialogueText').addEventListener('input',()=>renderDialogueLines());
