import {cleanWord,normalizeWord} from './utils.js';
const HEADERS=new Set(['word','english','vocabulary','vocab','tu','tu vung','từ','từ vựng','english word','word/phrase','phrase']);
function cleanCandidate(v){let s=cleanWord(v);if(!s)return null;for(const sep of ['\t',' - ',' – ',' — ',': ','; ']){const i=s.indexOf(sep);if(i>0){s=s.slice(0,i).trim();break}}if(!/[a-zA-Z]/.test(s))return null;if(s.length>120)return null;return s}
export function parsePasted(text){return String(text||'').split(/\r?\n/).map(cleanCandidate).filter(Boolean)}
export async function parseFile(file){const n=file.name.toLowerCase();if(n.endsWith('.xlsx'))return parseXlsx(await file.arrayBuffer());if(n.endsWith('.csv'))return parseCsv(await file.text());if(n.endsWith('.txt'))return parsePasted(await file.text());throw new Error('Chỉ hỗ trợ .xlsx, .csv, .txt')}
function parseCsv(text){const lines=String(text).split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const rows=lines.map(parseCsvLine);let col=0,start=0;const first=rows[0].map(x=>normalizeWord(x));const idx=first.findIndex(x=>HEADERS.has(x));if(idx>=0){col=idx;start=1}return rows.slice(start).map(r=>cleanCandidate(r[col]||'')).filter(Boolean)}
function parseCsvLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
async function parseXlsx(buffer){const zip=await unzipEntries(buffer,['xl/sharedStrings.xml','xl/worksheets/sheet1.xml']);const sheet=zip['xl/worksheets/sheet1.xml'];if(!sheet)throw new Error('Không tìm thấy sheet1 trong file .xlsx');const shared=zip['xl/sharedStrings.xml']?parseShared(zip['xl/sharedStrings.xml']):[];const rows=parseSheet(sheet,shared);if(!rows.length)return[];let col=0,start=0;const first=rows[0];for(const [k,v] of Object.entries(first)){if(HEADERS.has(normalizeWord(v))){col=Number(k);start=1;break}}if(start===0)col=Math.min(...Object.keys(first).map(Number));return rows.slice(start).map(r=>cleanCandidate(r[col]||'')).filter(Boolean)}
function parseShared(xmlText){const doc=new DOMParser().parseFromString(xmlText,'application/xml');return [...doc.querySelectorAll('si')].map(si=>[...si.querySelectorAll('t')].map(t=>t.textContent||'').join(''))}
function colIndex(ref){const m=String(ref).match(/^[A-Z]+/i);if(!m)return 0;let v=0;for(const ch of m[0].toUpperCase())v=v*26+(ch.charCodeAt(0)-64);return v-1}
function parseSheet(xmlText,shared){const doc=new DOMParser().parseFromString(xmlText,'application/xml');return [...doc.querySelectorAll('row')].map(row=>{const obj={};for(const c of row.querySelectorAll('c')){const idx=colIndex(c.getAttribute('r'));const type=c.getAttribute('t');let val='';if(type==='inlineStr')val=[...c.querySelectorAll('is t')].map(t=>t.textContent||'').join('');else{const raw=c.querySelector('v')?.textContent||'';val=type==='s'?(shared[Number(raw)]??''):raw}obj[idx]=val}return obj})}
async function unzipEntries(buffer,wanted){if(!('DecompressionStream'in globalThis))throw new Error('Safari này chưa hỗ trợ giải nén .xlsx trực tiếp. Hãy dùng CSV/TXT hoặc cập nhật iOS.');const bytes=new Uint8Array(buffer),dv=new DataView(buffer);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(dv.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error('File .xlsx không hợp lệ');const count=dv.getUint16(eocd+10,true),cdOffset=dv.getUint32(eocd+16,true);let p=cdOffset;const want=new Set(wanted),out={};for(let n=0;n<count;n++){if(dv.getUint32(p,true)!==0x02014b50)break;const method=dv.getUint16(p+10,true),compSize=dv.getUint32(p+20,true),nameLen=dv.getUint16(p+28,true),extraLen=dv.getUint16(p+30,true),commentLen=dv.getUint16(p+32,true),localOffset=dv.getUint32(p+42,true);const name=new TextDecoder().decode(bytes.slice(p+46,p+46+nameLen));if(want.has(name)){if(dv.getUint32(localOffset,true)!==0x04034b50)throw new Error('ZIP local header lỗi');const ln=dv.getUint16(localOffset+26,true),le=dv.getUint16(localOffset+28,true),start=localOffset+30+ln+le;const data=bytes.slice(start,start+compSize);let raw;if(method===0)raw=data;else if(method===8){const stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));raw=new Uint8Array(await new Response(stream).arrayBuffer())}else throw new Error(`ZIP compression ${method} chưa hỗ trợ`);out[name]=new TextDecoder().decode(raw)}p+=46+nameLen+extraLen+commentLen}return out}
export function toVocabItems(words){const seen=new Set();const out=[];for(const raw of words){const word=cleanCandidate(raw);if(!word)continue;const normalizedWord=normalizeWord(word);if(!normalizedWord||seen.has(normalizedWord))continue;seen.add(normalizedWord);out.push({word,normalizedWord,meaningVi:'',partOfSpeech:'',exampleEn:'',exampleVi:'',ipaUS:'',ipaUK:'',aiState:'PENDING',aiAttempts:0,aiUpdatedAt:null,lastError:null,isLearned:false,masteryScore:0,reviewCount:0,correctCount:0,wrongCount:0,correctStreak:0,lastReviewedAt:null,nextReviewAt:null,createdAt:Date.now()})}return out}
