import {getAll,addPhrasalBulk,updatePhrasal,getPhrasalByState,getAudio,putAudio} from './db.js';
import {enrichPhrasalBatch,generateSpeech} from './ai.js';
import {loadSetting} from './crypto.js';
import {playBlob,speakSystem} from './audio.js';
import {normalizeWord,escapeHtml,toast} from './utils.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let running=false;
export function setupPhrasal(){
 $('#addPhrasalBtn').onclick=()=>$('#phrasalImportDialog').showModal();
 $('#phrasalImportNow').onclick=importPhrasal;
 $('#phrasalSearch').oninput=refreshPhrasal;
 $('#phrasalList').onclick=e=>{const b=e.target.closest('[data-phrasal-id]');if(b)openPhrasal(Number(b.dataset.phrasalId))};
 $('#closePhrasalDetail').onclick=()=>$('#phrasalDetailDialog').close();
 refreshPhrasal(); setTimeout(runPhrasalEnrichment,700);
}
async function importPhrasal(){const arr=$('#pastePhrasal').value.split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean);if(!arr.length)return toast('Hãy nhập ít nhất một cụm động từ');const r=await addPhrasalBulk(arr);$('#phrasalImportResult').textContent=`Thêm mới ${r.added}, trùng bỏ qua ${r.duplicates}`;$('#phrasalImportResult').classList.remove('hidden');if(r.added){$('#pastePhrasal').value='';refreshPhrasal();runPhrasalEnrichment()}}
export async function refreshPhrasal(){const q=normalizeWord($('#phrasalSearch')?.value||''),all=await getAll('phrasal');const rows=all.filter(x=>!q||x.normalizedPhrase.includes(q)||normalizeWord(x.meanings?.[0]?.vi||'').includes(q)).sort((a,b)=>a.phrase.localeCompare(b.phrase));const ready=all.filter(x=>x.aiState==='READY').length;$('#phrasalCount').textContent=all.length;$('#phrasalProgress').textContent=`AI hoàn thiện: ${ready} / ${all.length}`;$('#phrasalList').innerHTML=rows.map(x=>`<div class="word-row"><div><b>${escapeHtml(x.phrase)}</b><br><small>${escapeHtml(x.meanings?.[0]?.vi||'Đang chờ AI')}</small></div><div class="word-row-actions"><span class="badge ${x.aiState==='READY'?'ok':'neutral'}">${x.aiState}</span>${x.aiState==='READY'?`<button class="secondary compact" data-phrasal-id="${x.id}">XEM / HỌC</button>`:''}</div></div>`).join('')||'<div class="empty-state">Chưa có cụm động từ.</div>'}
async function runPhrasalEnrichment(){if(running)return;running=true;try{while(document.visibilityState==='visible'){let pending=await getPhrasalByState('PENDING');if(!pending.length)break;const batch=pending.slice(0,10);for(const x of batch){x.aiState='PROCESSING';x.aiAttempts=(x.aiAttempts||0)+1;await updatePhrasal(x)}try{const result=await enrichPhrasalBatch(batch.map(x=>x.phrase));for(let i=0;i<batch.length;i++){const x=batch[i],d=result[i];if(d)Object.assign(x,d,{aiState:'READY',lastError:null,aiUpdatedAt:Date.now()});else{x.aiState='ERROR';x.lastError='AI thiếu dữ liệu'}await updatePhrasal(x)}}catch(e){for(const x of batch){x.aiState='PENDING';x.lastError=e.message;await updatePhrasal(x)}toast(`AI cụm động từ tạm dừng: ${String(e.message||e).slice(0,120)}`);break}await refreshPhrasal()}}finally{running=false;refreshPhrasal()}}
async function playCached(text,accent,key,id){let a=await getAudio(key);if(!a?.blob){try{const voice=await loadSetting(accent==='UK'?'wordVoiceUK':'wordVoiceUS','Kore');const blob=await generateSpeech(text,accent,voice,'vocabulary');await putAudio(key,blob,{phrasalId:id,accent});a={blob}}catch{return speakSystem(text,accent,1)}}return playBlob(a.blob,1)}
async function openPhrasal(id){const x=(await getAll('phrasal')).find(v=>v.id===id);if(!x)return;const meanings=(x.meanings||[]).map((m,mi)=>`<section class="pos-block"><div class="pos-title">NGHĨA ${mi+1}</div><div class="sense"><b>${escapeHtml(m.vi)}</b><div class="muted">${escapeHtml(m.explanation||'')}</div>${m.example?.en?`<div class="example">${escapeHtml(m.example.en)} <button class="mini-audio pv-audio" data-text="${escapeHtml(m.example.en)}" data-key="pv-example:${id}:${mi}:US" data-accent="US">🔊</button><br><span class="muted">${escapeHtml(m.example.vi||'')}</span></div>`:''}${m.synonyms?.length?`<div class="synonyms"><h4>Đồng nghĩa</h4>${m.synonyms.map((a,si)=>`<div class="synonym-item"><b>${escapeHtml(a.phrase)}</b> — ${escapeHtml(a.meaningVi||'')}<div class="ipa-row"><button class="audio-btn pv-audio" data-text="${escapeHtml(a.phrase)}" data-key="pv-syn:${id}:${mi}:${si}:UK" data-accent="UK">🇬🇧 ${escapeHtml(a.pronunciation?.uk||'—')} 🔊</button><button class="audio-btn pv-audio" data-text="${escapeHtml(a.phrase)}" data-key="pv-syn:${id}:${mi}:${si}:US" data-accent="US">🇺🇸 ${escapeHtml(a.pronunciation?.us||'—')} 🔊</button></div></div>`).join('')}</div>`:''}</div></section>`).join('');
 const components=(x.components||[]).map(c=>`<div class="component-item"><b>${escapeHtml(c.word)}</b> <span class="badge neutral">${escapeHtml(c.type)}</span><br>${escapeHtml(c.meaningVi)}<div class="muted">${escapeHtml(c.role)}</div></div>`).join('');
 $('#phrasalDetailContent').innerHTML=`<div class="learn-card"><div class="learn-word">${escapeHtml(x.phrase)}</div><div class="ipa-row"><button class="audio-btn pv-audio" data-text="${escapeHtml(x.phrase)}" data-key="pv:${id}:UK" data-accent="UK">🇬🇧 ${escapeHtml(x.ipaUK||'—')} 🔊</button><button class="audio-btn pv-audio" data-text="${escapeHtml(x.phrase)}" data-key="pv:${id}:US" data-accent="US">🇺🇸 ${escapeHtml(x.ipaUS||'—')} 🔊</button></div><div class="word-family"><h3>PHÂN TÍCH CỤM</h3>${components}</div>${meanings}</div>`;
 $$('.pv-audio').forEach(b=>b.onclick=()=>playCached(b.dataset.text,b.dataset.accent,b.dataset.key,id));$('#phrasalDetailDialog').showModal();prefetchPhrasalAudio(x)}
async function prefetchPhrasalAudio(x){const jobs=[{t:x.phrase,a:'UK',k:`pv:${x.id}:UK`},{t:x.phrase,a:'US',k:`pv:${x.id}:US`}];(x.meanings||[]).forEach((m,mi)=>{if(m.example?.en)jobs.push({t:m.example.en,a:'US',k:`pv-example:${x.id}:${mi}:US`});(m.synonyms||[]).forEach((s,si)=>{jobs.push({t:s.phrase,a:'UK',k:`pv-syn:${x.id}:${mi}:${si}:UK`},{t:s.phrase,a:'US',k:`pv-syn:${x.id}:${mi}:${si}:US`})})});for(const j of jobs){if(!(await getAudio(j.k)))try{const voice=await loadSetting(j.a==='UK'?'wordVoiceUK':'wordVoiceUS','Kore');const blob=await generateSpeech(j.t,j.a,voice,'vocabulary');await putAudio(j.k,blob,{phrasalId:x.id,accent:j.a})}catch{break}}}
