import {getAll,addPhrasalBulk,updatePhrasal,getPhrasalByState,getAudio,putAudio} from './db.js';
import {enrichPhrasalBatch,generateSpeech} from './ai.js';
import {loadSetting} from './crypto.js';
import {playBlob,speakSystem} from './audio.js';
import {normalizeWord,escapeHtml,toast} from './utils.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let running=false,learn=[],learnIndex=0,quiz=[],quizIndex=0,quizScore=0;
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export function setupPhrasal(){
 $('#addPhrasalBtn').onclick=()=>$('#phrasalImportDialog').showModal(); $('#phrasalImportNow').onclick=importPhrasal;
 $('#phrasalSearch').oninput=refreshPhrasal; $('#togglePhrasalListBtn').onclick=()=>{$('#phrasalListPanel').classList.toggle('hidden');refreshPhrasal()};
 $('#learn10PhrasalBtn').onclick=startLearn; $('#quizPhrasalBtn').onclick=startQuiz;
 $('#phrasalList').onclick=e=>{const b=e.target.closest('[data-phrasal-id]');if(b)openPhrasal(Number(b.dataset.phrasalId))};
 $('#closePhrasalDetail').onclick=()=>$('#phrasalDetailDialog').close(); $('#closePhrasalLearn').onclick=()=>$('#phrasalLearnDialog').close(); $('#closePhrasalQuiz').onclick=()=>$('#phrasalQuizDialog').close();
 refreshPhrasal(); setTimeout(runPhrasalEnrichment,700);
}
async function importPhrasal(){const arr=$('#pastePhrasal').value.split(/\r?\n|,/).map(x=>x.trim()).filter(Boolean);if(!arr.length)return toast('Hãy nhập ít nhất một cụm động từ');const r=await addPhrasalBulk(arr);$('#phrasalImportResult').textContent=`Thêm mới ${r.added}, trùng bỏ qua ${r.duplicates}`;$('#phrasalImportResult').classList.remove('hidden');if(r.added){$('#pastePhrasal').value='';refreshPhrasal();runPhrasalEnrichment()}}
export async function refreshPhrasal(){const q=normalizeWord($('#phrasalSearch')?.value||''),all=await getAll('phrasal');const rows=all.filter(x=>!q||x.normalizedPhrase.includes(q)||normalizeWord(x.meanings?.[0]?.vi||'').includes(q)).sort((a,b)=>a.phrase.localeCompare(b.phrase));const ready=all.filter(x=>x.aiState==='READY').length;$('#phrasalCount').textContent=all.length;$('#phrasalProgress').textContent=`AI hoàn thiện: ${ready} / ${all.length}`;$('#phrasalList').innerHTML=rows.map(x=>`<div class="word-row"><div><b>${escapeHtml(x.phrase)}</b><br><small>${escapeHtml(x.meanings?.[0]?.vi||'Đang chờ AI')}</small></div><div class="word-row-actions"><span class="badge ${x.aiState==='READY'?'ok':'neutral'}">${x.aiState}</span>${x.aiState==='READY'?`<button class="secondary compact" data-phrasal-id="${x.id}">XEM / HỌC</button>`:''}</div></div>`).join('')||'<div class="empty-state">Chưa có cụm động từ.</div>'}
async function runPhrasalEnrichment(){if(running)return;running=true;try{while(document.visibilityState==='visible'){let pending=await getPhrasalByState('PENDING');if(!pending.length)break;const batch=pending.slice(0,10);for(const x of batch){x.aiState='PROCESSING';x.aiAttempts=(x.aiAttempts||0)+1;await updatePhrasal(x)}try{const result=await enrichPhrasalBatch(batch.map(x=>x.phrase));for(let i=0;i<batch.length;i++){const x=batch[i],d=result[i];if(d)Object.assign(x,d,{aiState:'READY',lastError:null,aiUpdatedAt:Date.now()});else{x.aiState='ERROR';x.lastError='AI thiếu dữ liệu'}await updatePhrasal(x)}}catch(e){for(const x of batch){x.aiState='PENDING';x.lastError=e.message;await updatePhrasal(x)}toast(`AI cụm động từ tạm dừng: ${String(e.message||e).slice(0,120)}`);break}await refreshPhrasal()}}finally{running=false;refreshPhrasal()}}
async function playCached(text,accent,key,id){let a=await getAudio(key);if(!a?.blob){try{const voice=await loadSetting(accent==='UK'?'wordVoiceUK':'wordVoiceUS','Kore');const blob=await generateSpeech(text,accent,voice,'vocabulary');await putAudio(key,blob,{phrasalId:id,accent});a={blob}}catch{return speakSystem(text,accent,1)}}return playBlob(a.blob,1)}
function detailHtml(x,learning=false){const meanings=(x.meanings||[]).map((m,mi)=>`<section class="pos-block"><div class="pos-title">NGHĨA ${mi+1}</div><div class="sense"><b>${escapeHtml(m.vi)}</b><div class="muted">${escapeHtml(m.explanation||'')}</div>${m.example?.en?`<div class="example">${escapeHtml(m.example.en)} <button class="mini-audio pv-audio" data-text="${escapeHtml(m.example.en)}" data-key="pv-example:${x.id}:${mi}:US" data-accent="US">🔊</button><br><span class="muted">${escapeHtml(m.example.vi||'')}</span></div>`:''}${m.synonyms?.length?`<div class="synonyms"><h4>Đồng nghĩa</h4>${m.synonyms.map((a,si)=>`<div class="synonym-item"><b>${escapeHtml(a.phrase)}</b> — ${escapeHtml(a.meaningVi||'')}<div class="ipa-row"><button class="audio-btn pv-audio" data-text="${escapeHtml(a.phrase)}" data-key="pv-syn:${x.id}:${mi}:${si}:UK" data-accent="UK">🇬🇧 ${escapeHtml(a.pronunciation?.uk||'—')} 🔊</button><button class="audio-btn pv-audio" data-text="${escapeHtml(a.phrase)}" data-key="pv-syn:${x.id}:${mi}:${si}:US" data-accent="US">🇺🇸 ${escapeHtml(a.pronunciation?.us||'—')} 🔊</button></div></div>`).join('')}</div>`:''}</div></section>`).join('');const components=(x.components||[]).map(c=>`<div class="component-item"><b>${escapeHtml(c.word)}</b> <span class="badge neutral">${escapeHtml(c.type)}</span><br>${escapeHtml(c.meaningVi)}<div class="muted">${escapeHtml(c.role)}</div></div>`).join('');return `<div class="learn-card">${learning?`<div class="muted">${learnIndex+1} / ${learn.length}</div>`:''}<div class="learn-word">${escapeHtml(x.phrase)}</div><div class="ipa-row"><button class="audio-btn pv-audio" data-text="${escapeHtml(x.phrase)}" data-key="pv:${x.id}:UK" data-accent="UK">🇬🇧 ${escapeHtml(x.ipaUK||'—')} 🔊</button><button class="audio-btn pv-audio" data-text="${escapeHtml(x.phrase)}" data-key="pv:${x.id}:US" data-accent="US">🇺🇸 ${escapeHtml(x.ipaUS||'—')} 🔊</button></div><div class="word-family"><h3>PHÂN TÍCH CỤM</h3>${components}</div>${meanings}${learning?'<div class="learn-nav"><button id="pvDont" class="secondary">CHƯA NHỚ</button><button id="pvKnow" class="primary">ĐÃ NHỚ</button></div>':''}</div>`}
function bindAudio(root,x){root.querySelectorAll('.pv-audio').forEach(b=>b.onclick=()=>playCached(b.dataset.text,b.dataset.accent,b.dataset.key,x.id))}
async function openPhrasal(id){const x=(await getAll('phrasal')).find(v=>v.id===id);if(!x)return;$('#phrasalDetailContent').innerHTML=detailHtml(x);bindAudio($('#phrasalDetailContent'),x);$('#phrasalDetailDialog').showModal();prefetchPhrasalAudio(x)}
async function startLearn(){learn=shuffle((await getAll('phrasal')).filter(x=>x.aiState==='READY'&&!x.isLearned)).slice(0,10);if(!learn.length)return toast('Chưa có cụm chưa học nào đã READY.');learnIndex=0;$('#phrasalLearnDialog').showModal();renderLearn()}
function renderLearn(){const x=learn[learnIndex];if(!x){$('#phrasalLearnContent').innerHTML='<div class="empty-state"><b>Hoàn thành phiên học cụm động từ.</b></div>';refreshPhrasal();return}$('#phrasalLearnContent').innerHTML=detailHtml(x,true);bindAudio($('#phrasalLearnContent'),x);$('#pvDont').onclick=()=>gradeLearn(false);$('#pvKnow').onclick=()=>gradeLearn(true);prefetchPhrasalAudio(x)}
async function gradeLearn(ok){const x=learn[learnIndex];x.isLearned=true;x.reviewCount=(x.reviewCount||0)+1;x.lastReviewedAt=Date.now();if(ok){x.correctCount=(x.correctCount||0)+1;x.masteryScore=clamp((x.masteryScore||0)+12,0,100)}else{x.wrongCount=(x.wrongCount||0)+1;x.masteryScore=clamp((x.masteryScore||0)-8,0,100)}await updatePhrasal(x);learnIndex++;renderLearn()}
async function startQuiz(){const all=(await getAll('phrasal')).filter(x=>x.aiState==='READY'&&x.meanings?.[0]?.vi);if(all.length<4)return toast('Cần ít nhất 4 cụm READY để kiểm tra.');quiz=shuffle(all).slice(0,Math.min(10,all.length));quizIndex=0;quizScore=0;$('#phrasalQuizDialog').showModal();renderQuiz(all)}
function renderQuiz(all){const x=quiz[quizIndex];if(!x){$('#phrasalQuizContent').innerHTML=`<div class="empty-state"><b>Hoàn thành: ${quizScore}/${quiz.length}</b></div>`;refreshPhrasal();return}const wrong=shuffle(all.filter(a=>a.id!==x.id&&a.meanings?.[0]?.vi)).slice(0,3).map(a=>a.meanings[0].vi),correct=x.meanings[0].vi,opts=shuffle([correct,...wrong]);$('#phrasalQuizContent').innerHTML=`<div class="muted">${quizIndex+1} / ${quiz.length}</div><div class="quiz-question">${escapeHtml(x.phrase)}</div><div class="quiz-options">${opts.map(o=>`<button class="quiz-option" data-answer="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div>`;$('#phrasalQuizContent').querySelectorAll('.quiz-option').forEach(b=>b.onclick=async()=>{const ok=b.dataset.answer===correct;b.classList.add(ok?'correct':'wrong');if(ok)quizScore++;x.reviewCount=(x.reviewCount||0)+1;x.lastReviewedAt=Date.now();x.masteryScore=clamp((x.masteryScore||0)+(ok?10:-6),0,100);if(ok)x.correctCount=(x.correctCount||0)+1;else x.wrongCount=(x.wrongCount||0)+1;await updatePhrasal(x);setTimeout(()=>{quizIndex++;renderQuiz(all)},450)})}
async function prefetchPhrasalAudio(x){const jobs=[{t:x.phrase,a:'UK',k:`pv:${x.id}:UK`},{t:x.phrase,a:'US',k:`pv:${x.id}:US`}];(x.meanings||[]).forEach((m,mi)=>{if(m.example?.en)jobs.push({t:m.example.en,a:'US',k:`pv-example:${x.id}:${mi}:US`});(m.synonyms||[]).forEach((s,si)=>jobs.push({t:s.phrase,a:'UK',k:`pv-syn:${x.id}:${mi}:${si}:UK`},{t:s.phrase,a:'US',k:`pv-syn:${x.id}:${mi}:${si}:US`}))});for(const j of jobs){if(!(await getAudio(j.k)))try{const voice=await loadSetting(j.a==='UK'?'wordVoiceUK':'wordVoiceUS','Kore');const blob=await generateSpeech(j.t,j.a,voice,'vocabulary');await putAudio(j.k,blob,{phrasalId:x.id,accent:j.a})}catch{break}}}
